### ISSUE TITLE
#sort: on MooseGroup not working

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#2518] opened 2024-01-21 11:51 UTC
For example on packages, it always sorts on alphabetical order

Note: #sort: changes the internal collection and I don't see why ?!?
```St
MooseGroup >> sort: aBlock
	self entities: (self entities sorted: aBlock)
```
Apart from that, `(self entities sorted: aBlock)` works as expected

**Comment by jecisc** [comment] 2024-01-22 11:16
#sort: changes the internal collection because #sort: should not return a new one but order itself and return itself. 

I think we could improve it to ask to the internal collection to sort itself instead of creating a new one.

I tried to add some tests but for now they are passing (but at some point I tried to sort packages in an inspector and it did not work).

I'll do some more digging

**Comment by ClotildeToullec** [comment] 2024-01-22 12:54
#sort does work.
The problem is the display in the inspector. We have a sort by name block in MiNavigationBrowser>>#initializePresenters.
This has been a choice to always show entities in the same order but hides the actual order of the inner collection.

**Comment by jecisc** [comment] 2024-01-22 13:37
I did a PR to improve the implementation. https://github.com/moosetechnology/Famix/pull/692

Now about the inspector what Clotilde said makes sense. Should we close the issue?

**Comment by NicolasAnquetil** [comment] 2024-01-23 12:30
before closing

1. do we remove the automatic sorting in the inspector ? I would say yes because it is confusing (as was demonstrated)
2. can we fix the existing MooseGroup >> #sort: implementation ?

**Comment by jecisc** [comment] 2024-01-23 12:45
The 2 is done already.

For the 1 I am not sure what is the best (there is the raw view for real state of the object)

**Comment by ClotildeToullec** [comment] 2024-01-26 15:21
I think I found a solution. We could remove the automatic sorting but add the little arrows in the table, to do the sort when needed (as it is when inspecting an OrderedCollection for example)
What do you think?

**Comment by jecisc** [comment] 2024-01-26 15:26
I like it

**Comment by ClotildeToullec** [comment] 2024-01-29 10:01
Proposed fix here: https://github.com/moosetechnology/MooseIDE/pull/1004

**Closed as completed** 2024-01-29 10:08 UTC
