### ISSUE TITLE
Moose Panel: navigation dots don't allow scrolling one to the right

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1285] opened 2018-01-20 19:33 UTC
![image](https://user-images.githubusercontent.com/3233724/35187234-eb8cda72-fe20-11e7-8467-34cd8b4f8023.png)

When the navigation dots look like this, I see the leftmost two panels. Now I want to scroll one panel to the right, to see the second and third panel. To do this I click on the second dot. Nothing happens. In all other situations, clicking on a navigation dot shows the corresponding panel at the left, and the others next to it. The dots should behave consistently.

**Comment by girba** [comment] 2018-01-20 19:49
Indeed, this is less ideal. The issue is that the scrollbar goes above the buttons, and you can drag it to scroll. If we make the button clickable, this will conflict with the scrolling behavior. So, that is why we chose to not make those buttons clickable by adding the scrollbar on top of them.

**Comment by rillig** [comment] 2018-01-20 20:04
Cool. The scrolling feels very nice and smooth. I just didn't know this was a scroll bar. That might be because this scroll bar looks totally different from the one directly above it. :)

**Comment by Ducasse** [comment] 2018-03-17 10:08
I'm closing this issue to get a clean list.
Tx for the discussion

**Closed by Ducasse** 2018-03-17 10:08 UTC
