### ISSUE TITLE
Dirty packages after Roassal2(#stable) installation

### ISSUE THREAD

**Issue by vonbecmann** [moosetechnology/Moose#1141] opened 2016-08-25 19:05 UTC
" Dirty packages after Roassal2(#stable) installation
Pharo image: Pharo5.0#50761
Virtual machine used: CoInterpreter VMMaker.oscog-eem.1630 uuid: 2ed025ea-f400-4440-8e8b-5aa46d06c9ab Jan 17 2016
StackToRegisterMappingCogit VMMaker.oscog-eem.1630 uuid: 2ed025ea-f400-4440-8e8b-5aa46d06c9ab Jan 17 2016
https://github.com/estebanlm/pharo-vm.git Commit: 21ec004cce7d26010c18d357c805a0e1a4ffe376 Date: 2016-01-14 11:42:33 +0100 By: Esteban Lorenzano estebanlm@gmail.com Jenkins build #498

Platform Name: unix
Class browser used (if applicable): Nautilus

Steps to reproduce:
# . World>>Monticello Browser

no dirty packages.
# . evaluate

Metacello new
      smalltalkhubUser: 'ObjectProfile' project: 'Roassal2';
      configuration: 'Roassal2';
      version: #stable;
      load.
""linear load : 
    explicit load : 1.35 [ConfigurationOfRoassal2]
        load : ConfigurationOfNeoJSON-Sven...c-AlexandreBergel.13
        load : Roassal2GT-StefanReichhart.42
        load : Roassal2-Rules-YuriyTymchuk.2""
# .World>>Monticello Browser

Actual Result:
# . seven dirty packages.

RPackage organizer packages select: [ :each | each isDirty ] thenCollect: [ :each | each name ].
# (#'GT-Tests-Spotter' #'GT-Examples' #'GT-Inspector' #'GT-Examples-UI' #'GT-SpotterExtensions-Core' #'GT-Tests-Inspector' #'GT-InspectorExtensions-Core')

Expected Result:
# . no dirty packages

"

**Comment by klaranosan** [comment] 2018-03-16 13:03
we use the description to see if the problem is still in Pharo 6.1.
It is not: Roassal packages are not dirty. We suggest to close the issue.

**Closed** 2018-03-16 19:41 UTC
Labels: Roassal
